### PR TITLE
Add switch to toggle image

### PR DESCRIPTION
**Pull request by otakuchiyan**

### CODE REVIEW

**Comment by tobykurien** [comment]
Thanks for the pr @otakuchiyan - I will merge this in manually, as I do not want the intellij files in the project.

**Comment by otakuchiyan** [comment]
OK, I have been removed.

**Comment by tobykurien** [comment]
Thanks! I will have to merge the image toggle feature manually, since the pull request now includes some changes I don't like: drops support for older devices, adds invasive permissions, and I'm not sure what the GPlusActivity is doing yet. I'd prefer the app the share it's content using a share intent, rather than download files itself (if possible).

**Comment by otakuchiyan** [comment]
The GPlusActivity is order to integration for Google+, I want to make it can push the notifies of Google+ in notification area, but I have found it's too hard to get the notifies, so removed this activity. (Sorry for my poor english)

**Comment by tobykurien** [comment]
Aah ok! Yes the notification integration can be difficult - you'd need to create a service and call the Google API to get data for notifications. It can't be done from an Activity, since the Activity is paused when it's not showing.

**Comment by otakuchiyan** [comment]
And seems google+ haven't provide any API to get notifications...
Er...I whether to remove invasive permissions and resupport for older devices now?

**Comment by tobykurien** [comment]
Yes, please :-)

**Comment by otakuchiyan** [comment]
OK, I have been modified.

**Pull request merged**
